project:
  type: website

website:
  title: "Amber Tsao"
  navbar:
    left:
      - href: index.qmd
        text: Home

  page-footer:
    right: "&copy; 2024, Amber Tsao"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto

